# Generated by Django 4.0.3 on 2022-03-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_url', models.CharField(max_length=256)),
                ('github_readme', models.CharField(max_length=256)),
            ],
        ),
    ]
