# Generated by Django 4.0.3 on 2022-04-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='github_readme',
        ),
        migrations.AddField(
            model_name='project',
            name='project_description',
            field=models.CharField(default='Empty', max_length=512),
            preserve_default=False,
        ),
    ]
