# Generated by Django 4.0.4 on 2022-04-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_project_github_readme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tech_tags',
            field=models.CharField(default='Python', max_length=256),
            preserve_default=False,
        ),
    ]
