# Generated by Django 4.0.4 on 2022-04-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tech_tags',
        ),
        migrations.AddField(
            model_name='project',
            name='tech_tags',
            field=models.ManyToManyField(to='portfolio.tag'),
        ),
    ]
